### ISSUE TITLE
make new tab with list items

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/shiny_mobile_demo#1]
See if you can find some that look nice. e.g:

![22b71a2dc27fc00b4014e320941249c69571c72b](https://user-images.githubusercontent.com/4030554/76472306-9951b080-63cb-11ea-9a45-0ddca7e20441.png)

ignore the reb box above.  I copied this from someone else's screenshot, and they put in the red box.  We just want nice looking list items.

**Comment by nickmerl** [comment]
f1049ef0e7eba9be853507ad64270dc79ce7a78f

basic list item tab.  Not clickable yet.  Will look into how to make that work

**Comment by nickmerl** [comment]
the application is behaving strangely and there are still errors.  For example, the app doesn't navigate to the "back_test" tab when you click on it from the "graph" tab but does when you click on it from the "list" tab.  Also, the highlighting of the selected tab still doesn't work and I am still getting errors that I can't make sense of despite commenting out the code in the panel and replacing it with just a f7PanelItem.

f776ddf12fba631845877a8451c1e284c5c08a17

**Comment by nickmerl** [comment]
54114861a880a4abab568d256ac6966bbb7bf955

fixed tab behavior issues
